const assert=require('assert');
const pb=require('../assets/athlete-personal-bests');
const athlete={name:'Mark Sample',contactId:'a'};
assert(pb.matches({athleteId:'a',name:'Other'},athlete));
assert(!pb.matches({athleteId:'other',name:'Mark Sample'},athlete));
assert(pb.matches({athleteName:' MARK   SAMPLE '},athlete));
assert(!pb.matches({},athlete));
assert.strictEqual(pb.seconds('1:23.4'),83.4);
assert.strictEqual(pb.seconds('DNF'),null);
assert.strictEqual(pb.seconds('1:80'),null);
assert.strictEqual(pb.measurement('16-8').value,200);
assert.strictEqual(pb.measurement('NM'),null);
assert.strictEqual(pb.measurement('22'),null);
const practices=[{id:'s',date:'2026-09-01',surface:'Track',timingMethod:'FAT',speedMetrics:[{athleteId:'a',metric:'30m Fly',distance:30,unit:'m',seconds:3.9},{athleteId:'a',metric:'30m Fly',distance:30,unit:'m',seconds:3.8},{athleteId:'other',metric:'30m Fly',seconds:1}]},{id:'later',date:'2026-09-02',surface:'Track',timingMethod:'FAT',speedMetrics:[{athleteId:'a',metric:'30m Fly',distance:30,unit:'m',seconds:4},{athleteId:'a',metric:'30m Fly',distance:30,unit:'m',seconds:4.1}]},{id:'turf',date:'2026-09-03',surface:'Turf',timingMethod:'FAT',speedMetrics:[{athleteId:'a',metric:'30m Fly',distance:30,unit:'m',seconds:3}]}];
const speed=pb.summarize(pb.speed(practices,athlete));
assert.strictEqual(speed.length,2);
const track=speed.find(r=>r.context.includes('Track'));
assert.strictEqual(track.best.value,3.8);
assert.strictEqual(track.latest.value,4);
const data={rackSessions:[{id:'r',status:'complete',date:'2026-09-01',athletes:[{id:'a',name:'Mark Sample',results:[{exerciseName:'Back Squat',actualValue:135,unit:'lb',actualReps:5},{exerciseName:'Back Squat',actualValue:155,unit:'lb',actualReps:3},{exerciseName:'Back Squat',actualValue:70,unit:'kg',actualReps:5},{exerciseName:'Broad Jump',actualValue:86,unit:'in',actualReps:1},{exerciseName:'Back Squat 1RM',actualValue:180,unit:'lb'},{exerciseName:'Back Squat Volume Load',actualValue:1800,unit:'lb'},{exerciseName:'Banded Squat',actualValue:10,unit:'lb',actualReps:5},{exerciseName:'Back Squat',actualValue:50,unit:'lb',actualReps:10,executionMode:'each_side'}]}]}],sessions:[{id:'legacy',date:'2026-09-01',rows:[{athleteId:'a',marks:{bench:'100 lb'}}]}]};
const power=pb.power(data,athlete);
assert.strictEqual(power.estimates.length,1);
assert.strictEqual(power.field.length,1);
assert.strictEqual(pb.strength(power.strength,'5').length,2);
assert.strictEqual(pb.strength(power.strength,'3').length,1);
assert.strictEqual(pb.strength(power.strength,'unknown').length,1);
assert.strictEqual(pb.estimatedMax(power.strength[0]),null,'unknown execution is not assumed bilateral');
assert.strictEqual(pb.estimatedMax({...power.strength[0],context:'Standard'}),157.5);
assert.strictEqual(pb.estimatedMax({label:'Back Squat',reps:20,context:'Standard',value:135}),null);
assert.strictEqual(pb.estimatedMax({label:'DB Raise',reps:5,context:'Standard',value:20}),null);
assert.strictEqual(pb.estimatedMax({label:'Back Squat',reps:5,context:'Each side',value:20}),null);
assert.strictEqual(pb.power({...data,rackSessions:[{...data.rackSessions[0],status:'active'}]},athlete).field.length,0);
const field=pb.field([{id:'f',date:'2026-09-01',event:'High Jump',athleteId:'a',height:'6-0',attempts:[{result:'X',height:'6-0'},{result:'O',height:'5-8'}]},{id:'group',date:'2026-09-02',event:'Long Jump',athleteSummaries:[{athleteId:'a',bestMark:'16-8'}]}],athlete);
assert.strictEqual(field.length,2);
assert.strictEqual(field[0].value,68,'missed and merely planned heights cannot become PRs');
const meets=[{contactId:'a',event:'100m',resultDisplay:'13.4',meetDate:'2026-09-01',wind:'1.0'},{contactId:'a',event:'100m',resultDisplay:'12.9',meetDate:'2026-09-02',wind:'3.0'},{contactId:'a',event:'Long Jump',resultDisplay:'16-8',meetDate:'2026-09-02',resultType:'field'},{contactId:'a',event:'100m',resultDisplay:'1.0',meetDate:'2026-09-02',voided:true},{contactId:'a',event:'4x100m',resultDisplay:'55.4',meetDate:'2026-09-02',resultType:'relay'}];
assert.strictEqual(pb.meets(meets.concat(meets),athlete).length,3);
assert.strictEqual(pb.summarize(pb.meets(meets,athlete)).length,3,'wind-assisted results remain separate');
assert(pb.meets([{...meets[0],wind:'NWI'}],athlete)[0].context.includes('Wind unrecorded'));
assert.strictEqual(pb.summarize([{...track.best,date:'2026-09-03'},{...track.best,date:'2026-09-01'}])[0].best.date,'2026-09-01');
const html=pb.renderTable([{...track,label:'<script>alert(1)</script>'}],false);
assert(html.includes('&lt;script&gt;'));
assert(!html.includes('<script>'));
assert(pb.renderTable([],false).includes('No comparable'));
console.log('Athlete personal best comparison tests passed');
