const assert = require('assert');
const fs = require('fs');
const { rows } = require('../assets/power-trak-rack-history');
const completed = { id:'rack-1', status:'complete', date:'2026-09-27', workoutName:'Strength', rackName:'Inside', athletes:[{ name:'Mark Sample', rackStatus:'complete', results:[{ exerciseName:'Squat', round:2, actualReps:20, actualValue:0, unit:'lb', leftReps:10, rightReps:10 }] }] };
const input = [completed, { ...completed, id:'active', status:'active' }, { ...completed, id:'ended', athletes:[{name:'Other',rackStatus:'released',results:[]}] }];
const original = JSON.stringify(input);
const result = rows(input);
assert.strictEqual(result.length,2);
assert.strictEqual(result[0].athlete,'Mark Sample');
assert.strictEqual(result[0].reps,20);
assert.strictEqual(result[0].result,'0 lb');
assert.strictEqual(result[0].set,'Set 2');
assert.strictEqual(result[0].sides,'L 10 / R 10');
assert.strictEqual(result[1].status,'Stopped early');
assert.strictEqual(result[1].result,'--');
assert.strictEqual(rows(input,{search:'mark sample'}).length,1);
assert.strictEqual(rows(input,{start:'2026-09-28'}).length,0);
assert.strictEqual(rows(input,{end:'2026-09-26'}).length,0);
assert.strictEqual(rows([{...completed,id:'power_import_1',athletes:[{name:'Imported',results:[{exerciseName:'Bench',rep:3,actualValue:135,unit:'lb'}]}]}])[0].status,'Imported');
assert.strictEqual(JSON.stringify(input),original);
const html=fs.readFileSync('power-trak.html','utf8');
assert(html.includes('/assets/power-trak-rack-history.js'));
assert(html.includes('renderRackSessionsCore();renderRackHistory()'));
assert(html.includes('data-history-rack='));
assert(html.includes('state.openRackSessionId=button.getAttribute'));
console.log('Power Trak completed rack history tests passed');
