const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const { rows } = require('../assets/power-trak-rack-history');
const completed = { id:'rack-1', status:'complete', date:'2026-09-27', workoutName:'Strength', rackName:'Inside', athletes:[{ name:'Mark Sample', rackStatus:'complete', results:[{ exerciseName:'Squat', round:2, actualReps:20, actualValue:0, unit:'lb', leftReps:10, rightReps:10 }] }] };
const input = [completed, { ...completed, id:'active', status:'active' }, { ...completed, id:'ended', athletes:[{name:'Other',rackStatus:'released',results:[]}] }];
const original = JSON.stringify(input);
const result = rows(input);
assert.strictEqual(result.length,2);
assert.strictEqual(result[0].athlete,'Mark Sample');
assert.strictEqual(result[0].reps,20);
assert.strictEqual(result[0].result,'0 lb');
assert.strictEqual(result[0].set,'Set 2');
assert.strictEqual(result[0].sides,'L 10 / R 10');
assert.strictEqual(result[1].status,'Stopped early');
assert.strictEqual(result[1].result,'--');
assert.strictEqual(rows(input,{search:'mark sample'}).length,1);
assert.strictEqual(rows(input,{start:'2026-09-28'}).length,0);
assert.strictEqual(rows(input,{end:'2026-09-26'}).length,0);
assert.strictEqual(rows([{...completed,id:'power_import_1',athletes:[{name:'Imported',results:[{exerciseName:'Bench',rep:3,actualValue:135,unit:'lb'}]}]}])[0].status,'Imported');
assert.strictEqual(JSON.stringify(input),original);
const html=fs.readFileSync('power-trak.html','utf8');
assert(html.includes('/assets/power-trak-rack-history.js'));
assert(html.includes("if(!els.historyPanel.hidden){applyFilters();renderRackHistory()}"));
assert(html.includes('rows.slice(0,rackHistoryVisibleCount)'));
assert(html.includes('id="rackHistoryMoreBtn"'));
assert(html.includes('id="rackSessionsMoreBtn"'));
assert(html.includes('visibleRacks=racks.slice(0,rackSessionVisibleCount)'));
assert(html.includes('data-history-rack='));
assert(html.includes('state.openRackSessionId=button.getAttribute'));
const elements=Object.fromEntries(['rackHistoryCount','exportRackHistoryBtn','rackHistoryRows','rackHistoryMoreBtn'].map(id=>[id,{}]));
const historyRender=html.slice(html.indexOf('var rackHistoryVisibleCount=100;'),html.indexOf("['rackHistorySearch'",html.indexOf('var rackHistoryVisibleCount=100;')));
const context={document:{getElementById:id=>elements[id]},rackHistoryRows:()=>Array.from({length:230},(_,i)=>({rackId:'rack-'+i,date:'2026-09-28',workout:'Strength',rack:'A',athlete:'Mark',exercise:'Squat',set:'Set 1',reps:5,result:'135 lb',status:'Complete'})),esc:value=>String(value),formatDate:value=>value,Set,Math};
vm.runInNewContext(historyRender,context);
context.renderRackHistory();
assert.strictEqual((elements.rackHistoryRows.innerHTML.match(/<tr>/g)||[]).length,100);
assert.strictEqual(elements.rackHistoryMoreBtn.hidden,false);
context.rackHistoryVisibleCount=200;
context.renderRackHistory();
assert.strictEqual((elements.rackHistoryRows.innerHTML.match(/<tr>/g)||[]).length,200);
assert.strictEqual(elements.rackHistoryCount.textContent,'230 sessions');
console.log('Power Trak completed rack history tests passed');
